"use strict";
var Project_1 = require("../Model/Project");
var ResourceType_1 = require("../Model/Resources/ResourceType");
var Schedulable_1 = require("../Model/Schedulable");
var Duration_1 = require("../Model/WorkingCalendar/Duration");
var WorkingCalendar_1 = require("../Model/WorkingCalendar/WorkingCalendar");
var WorkingDay_1 = require("../Model/WorkingCalendar/WorkingDay");
var WorkingHour_1 = require("../Model/WorkingCalendar/WorkingHour");
var ResourceUsage_1 = require("../Model/Resources/ResourceUsage");
var Dependency_1 = require("../Model/Dependency");
var Summary_1 = require("../Model/Summary");
var SpecialDay_1 = require("../Model/WorkingCalendar/SpecialDay");
var ProjectGenerator = (function () {
    function ProjectGenerator() {
    }
    ProjectGenerator.generateProject = function () {
        var resourceType = new ResourceType_1.ResourceType();
        resourceType.id = this.idCtr++;
        resourceType.available = 5;
        resourceType.name = "Senior developer";
        var resourceType2 = new ResourceType_1.ResourceType();
        resourceType2.id = this.idCtr++;
        resourceType2.available = 2;
        resourceType2.name = "Junior developer";
        var project = new Project_1.Project();
        var task11 = new Schedulable_1.Schedulable();
        task11.name = 'Task1';
        task11.description = 'First task of phase 1';
        task11.duration = new Duration_1.Duration();
        task11.duration.day = 1;
        task11.duration.hour = 0;
        task11.duration.minute = 0;
        task11.id = this.idCtr++;
        var task12 = new Schedulable_1.Schedulable();
        task12.name = 'Task2';
        task12.description = 'Second task of phase 1';
        task12.duration = new Duration_1.Duration();
        task12.duration.day = 0;
        task12.duration.hour = 10;
        task12.duration.minute = 0;
        task12.id = this.idCtr++;
        var dep12 = new Dependency_1.Dependency();
        dep12.id = this.idCtr++;
        dep12.task = task11;
        task12.predecessors.push(dep12);
        var dep12re = new Dependency_1.Dependency();
        dep12re.id = this.idCtr++;
        dep12re.task = task12;
        task11.successors.push(dep12re);
        var phase1 = new Summary_1.Summary();
        phase1.name = 'Phase 1';
        phase1.description = 'Summary of phase 1';
        phase1.id = this.idCtr++;
        phase1.tasks.push(task11);
        phase1.tasks.push(task12);
        task11.parent = phase1;
        task12.parent = phase1;
        var res1 = new ResourceUsage_1.ResourceUsage();
        res1.id = this.idCtr++;
        res1.resource = resourceType;
        res1.need = 2;
        phase1.resourceUsages.push(res1);
        var task21 = new Schedulable_1.Schedulable();
        task21.name = 'Task3';
        task21.description = 'First task of phase 2';
        task21.duration = new Duration_1.Duration();
        task21.duration.day = 1;
        task21.duration.hour = 0;
        task21.duration.minute = 0;
        task21.id = this.idCtr++;
        var task22 = new Schedulable_1.Schedulable();
        task22.name = 'Task4';
        task22.description = 'Second task of phase 2';
        task22.duration = new Duration_1.Duration();
        task22.duration.day = 0;
        task22.duration.hour = 20;
        task22.duration.minute = 0;
        task22.id = this.idCtr++;
        var dep22Duration = new Duration_1.Duration();
        dep22Duration.day = 1;
        var dep22 = new Dependency_1.Dependency();
        dep22.task = task21;
        dep22.id = this.idCtr++;
        dep22.lag = dep22Duration;
        task22.predecessors.push(dep22);
        var dep22re = new Dependency_1.Dependency();
        dep22re.task = task22;
        dep22re.id = this.idCtr++;
        dep22re.lag = dep22Duration;
        task21.successors.push(dep22re);
        var phase2 = new Summary_1.Summary();
        phase2.name = 'Phase 2';
        phase2.description = 'Summary of phase 2';
        phase2.id = this.idCtr++;
        var dep2 = new Dependency_1.Dependency();
        dep2.id = this.idCtr++;
        dep2.task = phase1;
        phase2.predecessors.push(dep2);
        var dep2re = new Dependency_1.Dependency();
        dep2re.id = this.idCtr++;
        dep2re.task = phase2;
        phase1.successors.push(dep2re);
        var res2 = new ResourceUsage_1.ResourceUsage();
        res2.id = this.idCtr++;
        res2.resource = resourceType;
        res2.need = 1;
        phase2.resourceUsages.push(res2);
        phase2.tasks.push(task21);
        phase2.tasks.push(task22);
        phase2.id = this.idCtr++;
        task21.parent = phase2;
        task22.parent = phase2;
        var task3 = new Schedulable_1.Schedulable();
        task3.name = 'Task5';
        task3.description = 'Independent task';
        task3.duration = new Duration_1.Duration();
        task3.duration.day = 0;
        task3.duration.hour = 20;
        task3.duration.minute = 0;
        task3.id = this.idCtr++;
        var res3 = new ResourceUsage_1.ResourceUsage();
        res3.id = this.idCtr++;
        res3.resource = resourceType;
        res3.need = 1;
        task3.resourceUsages.push(res3);
        project.tasks = [];
        project.tasks.push(phase1);
        project.tasks.push(phase2);
        project.tasks.push(task3);
        project.start = new Date();
        project.start.setHours(0, 0, 0, 0);
        var workingCalendar = WorkingCalendar_1.WorkingCalendar.getWorkingCalendar();
        var sday1 = new WorkingDay_1.WorkingDay();
        sday1.workingHours.push(new WorkingHour_1.WorkingHour(10, 0, 10, 10));
        workingCalendar.specialDays.add(new SpecialDay_1.SpecialDay(new Date(), sday1));
        project.workingCalendar = workingCalendar;
        project.resourceTypes.push(resourceType);
        project.resourceTypes.push(resourceType2);
        project.name = "Test project";
        return project;
    };
    ProjectGenerator.idCtr = 0;
    return ProjectGenerator;
}());
exports.ProjectGenerator = ProjectGenerator;
//# sourceMappingURL=ProjectGenerator.js.map